#!/bin/bash

# check if a filename was provided
if [ $# -eq 0 ]; then
  echo "Usage: $0 <filename>"
  exit 1
fi


# open vi with the provided filename
vi "+set nu" "$1"


# ask if file should be checked using pycodestyle
read -p "Do you want to check the file using pycodestyle? (y/n) " check

if [ "$check" == "y" ] || [ "$check" == "Y" ]; then
  # run pycodestyle
  if ! pycodestyle "$1"; then
    echo "pycodestyle check failed for file: $1"
    exit 1
  fi
fi

